version: '3'
services:
    platform_app:
        image: registry.gitlab.com/wondervoyage/platform
        container_name: platform
        ports:
           - 9080:9080
       # environment:
       #    - PGADMIN_DEFAULT_EMAIL=gary.chang.2.0@gmail.com
       #    - PGADMIN_DEFAULT_PASSWORD=n4925173
        depends_on:
           - pgdb
           - redis
        links:
           - pgdb
           - redis
           
    pgdb:
        image: postgres:10.5   
        container_name: platform_pgdb
        ports:
           - 15432:5432
        environment:
           - POSTGRES_USER=platformer
           - POSTGRES_PASSWORD=postgres
           - POSTGRES_DB=platform_db

    redis:
        image: redis:5.0
        container_name: platform_redis
        ports:
           - 6379:6379

    apidoc:
        image: swaggerapi/swagger-ui
        container_name: swagger-ui
        ports:
           - 9090:8080
        environment:
           - API_URL=http://128.199.88.117:9080/static/apidoc.yaml
         #  - API_URL=http://192.168.1.4:9080/static/apidoc.yaml
        depends_on:
           - platform_app
        links:
           - platform_app
        
        